const O=[1.42, 2.18, 1.07, 3.64, 1.31, 1.88, 5.12, 1.16, 2.73, 1.54, 4.21, 1.09, 2.46, 1.67, 3.18];
let i=0,b=10000,running=false,timer=null,count=null,entries=[],queue=[],hist=[],user=null;
const $=x=>document.getElementById(x),money=x=>x.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
function auth(mode='login'){let register=mode==='register';$('authForm').innerHTML=`<div class="form"><label>Phone number</label><input id="phone" placeholder="+254 7XX XXX XXX"><label>Password</label><input id="pass" type="password" placeholder="Password">${register?'<label>Confirm password</label><input id="pass2" type="password" placeholder="Confirm password">':''}<button class="submit" id="authBtn">${register?'Create account':'Login'}</button></div>`;$('authBtn').onclick=()=>{let p=$('phone').value.trim(),pw=$('pass').value;if(!p||!pw)return alert('Enter phone number and password');if(register&&pw!==$('pass2').value)return alert('Passwords do not match');showOtp(p)}}
function showOtp(p){$('authForm').innerHTML=`<div class="form"><label>One-time code</label><input id="otp" maxlength="6" placeholder="Enter code"><div class="otp">Demo verification code: 246810</div><button class="submit" id="verify">Verify & continue</button></div>`;$('verify').onclick=()=>{if($('otp').value!=='246810')return alert('Incorrect code');user=p;$('userPhone').textContent=p;$('auth').classList.add('hidden');$('app').classList.remove('hidden');startCycle()}}
$('loginTab').onclick=()=>{loginTab.classList.add('active');registerTab.classList.remove('active');auth('login')};$('registerTab').onclick=()=>{registerTab.classList.add('active');loginTab.classList.remove('active');auth('register')};auth();
function beep(f=440,d=.08){try{let A=AudioContext||webkitAudioContext,a=new A(),o=a.createOscillator(),g=a.createGain();o.frequency.value=f;g.gain.value=.035;o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+d)}catch(e){}}
function render(){$('bal').textContent=money(b);$('entries').innerHTML=entries.map((e,n)=>`<div class="entry"><input placeholder="Entry ${n+1}" value="${e.name}" oninput="entries[${n}].name=this.value"><input type="number" min="1" value="${e.amount}" oninput="entries[${n}].amount=+this.value"><button onclick="entries[${n}].auto=!entries[${n}].auto">${e.auto?'AUTO CASH':'CASH OUT'}</button><button class="remove" onclick="entries.splice(${n},1);render()">×</button></div>`).join('')}
function add(){if(entries.length<5){entries.push({name:'',amount:100,auto:false});render()}}
function reset(){$('mult').textContent='1.00x';$('plane').style.left='4%';$('plane').style.bottom='8%';$('trail').style.width='0';$('trail').style.height='0';$('crash').style.display='none'}
function startCycle(){reset();$('state').textContent='NEXT ROUND';let n=2;$('clock').textContent='STARTING '+n;count=setInterval(()=>{n--;if(n<1){clearInterval(count);startRound()}else $('clock').textContent='STARTING '+n},600)}
function startRound(){if(queue.length){entries=queue;queue=[]}let total=entries.reduce((s,e)=>s+Math.max(0,+e.amount||0),0);if(total>b){entries=[];render();return startCycle()}b-=total;render();running=true;$('state').textContent='FLYING';$('clock').textContent='IN PLAY';beep(520,.07);let target=O[i],st=performance.now(),dur=3000+target*850;timer=setInterval(()=>{let p=Math.min(1,(performance.now()-st)/dur),m=1+(target-1)*p;$('mult').textContent=m.toFixed(2)+'x';$('plane').style.left=(4+90*p)+'%';$('plane').style.bottom=(8+76*p)+'%';$('plane').style.transform='rotate(-'+(16-9*p)+'deg)';$('trail').style.width=(20+95*p)+'%';$('trail').style.height=(5+95*p)+'%';if(p>=1)crash()},25)}
function crash(){clearInterval(timer);running=false;$('state').textContent='CRASH';$('clock').textContent='NEXT ROUND';$('mult').textContent=O[i].toFixed(2)+'x';$('crash').style.display='block';beep(120,.18);beep(75,.22);hist.unshift(O[i]);hist=hist.slice(0,7);$('history').innerHTML=hist.map(x=>`<div class="r"><span>Completed</span><span>${x.toFixed(2)}x</span><span>Crash</span></div>`).join('');i=(i+1)%O.length;entries=[];render();setTimeout(startCycle,900)}
function place(){if(running){queue=entries.map(x=>({...x}));entries=[];render();$('state').textContent='QUEUED FOR NEXT ROUND'}else startRound()}
function wallet(kind){$('mt').textContent=kind;$('amt').value='';$('modal').style.display='flex';$('ok').onclick=()=>{let n=+$('amt').value;if(!n||n<1)return;b=kind==='Deposit'?b+n:Math.max(0,b-n);render();$('modal').style.display='none'}}
$('add').onclick=add;$('place').onclick=place;$('dep').onclick=()=>wallet('Deposit');$('wit').onclick=()=>wallet('Withdraw');$('close').onclick=()=>modal.style.display='none';add();render();