const outcomes=[1.42, 2.18, 1.07, 3.64, 1.31, 1.88, 5.12, 1.16, 2.73, 1.54, 4.21, 1.09, 2.46, 1.67, 3.18];
let idx=0,balance=10000,running=false,timer=null,entries=[],roundHistory=[];
const $=id=>document.getElementById(id);
function money(x){return x.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}
function beep(freq=440,d=.08){try{let A=AudioContext||webkitAudioContext,a=new A(),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;g.gain.value=.035;o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+d)}catch(e){}}
function renderBalance(){$('balance').textContent=money(balance)}
function renderBets(){let h='';entries.forEach((e,i)=>h+=`<div class="betrow"><input placeholder="Entry ${i+1}" value="${e.name}" oninput="entries[${i}].name=this.value"><input type="number" min="1" value="${e.amount}" oninput="entries[${i}].amount=Number(this.value)"><button onclick="entries[${i}].auto=!entries[${i}].auto">${e.auto?'AUTO CASH':'CASH OUT'}</button><button class="remove" onclick="entries.splice(${i},1);renderBets()">×</button></div>`);$('betRows').innerHTML=h}
function addEntry(){if(entries.length>=5)return alert('Maximum 5 entries per round.');entries.push({name:'',amount:100,auto:false});renderBets()}
function showModal(title,text,body,action){$('modalTitle').textContent=title;$('modalText').textContent=text;$('modalBody').innerHTML=body||'';$('modalAction').textContent=action||'Continue';$('modal').style.display='flex'}
function closeModal(){$('modal').style.display='none'}
function accountFlow(signin=false){showModal(signin?'Sign in':'Create account','Use a phone number and password. The one-time code below is simulated for this classroom prototype.','<input id="phone" placeholder="Phone number"><input id="pass" type="password" placeholder="Password">','Send code');$('modalAction').onclick=()=>{let p=$('phone').value.trim();if(!p)return;showModal('One-time code','A demonstration OTP has been generated. Enter it to continue.','<input id="otp" maxlength="6" placeholder="6-digit code"><p class="muted">Demo code: 246810</p>','Verify');$('modalAction').onclick=()=>{if($('otp').value==='246810'){$('phoneLabel').textContent=p;$('accountLabel').textContent=p;$('modalTitle').textContent='Account verified';$('modalText').textContent='Signed in successfully.';$('modalBody').innerHTML='';$('modalAction').onclick=closeModal}else alert('Incorrect code')}}}
function walletAction(kind){showModal(kind==='deposit'?'Deposit':'Withdraw','Enter an amount for the classroom account.','<input id="amount" type="number" min="1" placeholder="Amount">',kind==='deposit'?'Deposit':'Withdraw');$('modalAction').onclick=()=>{let n=Number($('amount').value);if(!n||n<1)return;if(kind==='deposit')balance+=n;else balance=Math.max(0,balance-n);renderBalance();closeModal()}}
function resetGame(){clearInterval(timer);running=false;$('status').textContent='WAITING';$('multiplier').textContent='1.00x';$('plane').style.left='5%';$('plane').style.bottom='8%';$('trail').style.width='0';$('trail').style.height='0';$('crash').style.display='none'}
function startRound(){if(running)return;if(!entries.length){addEntry();return}let total=entries.reduce((s,e)=>s+Math.max(0,Number(e.amount)||0),0);if(total>balance)return alert('Insufficient balance');balance-=total;renderBalance();running=true;$('status').textContent='FLYING';beep(540,.07);let target=outcomes[idx],start=performance.now(),duration=2600+target*750;
timer=setInterval(()=>{let p=Math.min(1,(performance.now()-start)/duration);let m=1+(target-1)*p;$('multiplier').textContent=m.toFixed(2)+'x';$('plane').style.left=(5+88*p)+'%';$('plane').style.bottom=(8+72*p)+'%';$('plane').style.transform='rotate(-'+(16-9*p)+'deg)';$('trail').style.width=(20+80*p)+'%';$('trail').style.height=(5+90*p)+'%';
entries.forEach(e=>{if(e.auto&&!e.done&&m>=1.5){let a=Number(e.amount)||0;balance+=a*m;e.done=true;renderBalance();beep(760,.07)}});if(p>=1)crashRound()},25)}
function crashRound(){clearInterval(timer);running=false;$('status').textContent='CRASH';$('multiplier').textContent=outcomes[idx].toFixed(2)+'x';$('crash').style.display='block';beep(130,.18);beep(85,.22);roundHistory.unshift(outcomes[idx]);roundHistory=roundHistory.slice(0,6);$('history').innerHTML=roundHistory.map(x=>`<div class="row"><span>Round</span><span class="red">${x.toFixed(2)}x</span><span>Crash</span></div>`).join('');idx=(idx+1)%outcomes.length;setTimeout(resetGame,1200)}
$('addBet').onclick=addEntry;$('placeAll').onclick=startRound;$('deposit').onclick=()=>walletAction('deposit');$('withdraw').onclick=()=>walletAction('withdraw');$('signupBtn').onclick=()=>accountFlow(false);$('signinBtn').onclick=()=>accountFlow(true);$('closeModal').onclick=closeModal;$('modalAction').onclick=closeModal;
addEntry();
